name : Testing aws logins

on:
  push:
    branches: [main]

jobs:
  Testing_aws_logins:
    name: Testing aws logins
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::416094998479:role/iam-action-role
          aws-region: us-east-2

      - name: coping text file to s3 bucket
        run : aws s3 cp file1.txt s3://mskrishna2808